### ISSUE TITLE
Design the Boss Mechanics

### ISSUE THREAD

**Issue by HectorBonada** [azsumas/HorrorShooter#11]
# Descripción
- [x] Diseño de las mecánicas del boss. 

**EXPECTED RESULTS:**

_Diseño total de las mecánicas del boss; su comportamiento, ataques, fases, etc._ Resultados finales [aquí](https://github.com/azsumas/HorrorShooter/wiki/Project-Description#boss).

**Comment by MinYoungSoo** [comment]
Boss mechanics in the [wiki](https://github.com/azsumas/HorrorShooter/wiki/Project-Description#boss). 
Boss animations also in the [wiki](https://github.com/azsumas/HorrorShooter/wiki/Assets-Needed#animation).
