### ISSUE TITLE
Design and Program the Main Menu

### ISSUE THREAD

**Issue by azsumas** [azsumas/HorrorShooter#19]
# Descripción
- [x] Press Start.
- [x] Main menu: New Game. Load Game. Options. Credits. Exit.

**EXPECTED RESULTS:**

_Pantalla de título funcional, con las diferentes opciones decididas en el [Game Flow del HDD](https://github.com/azsumas/HorrorShooter/wiki/Project-Description#menu-flow)._ Resultados finales [aquí](https://github.com/azsumas/HorrorShooter/blob/master/Mockup/mockup_main_screen_01.png).

**Comment by azsumas** [comment]
- Press Start.
- Main menu: New Game. Load Game. Options. Credits. Exit.
- Options: Resolution. Full screen. General volume. Muisc volume, effects. Quality.

**Comment by MinYoungSoo** [comment]
Final result in https://github.com/azsumas/HorrorShooter/commit/b2a8b434ec6511978024798b5b123d0ef8ceb557 commit. 
Previous and new version.
