### ISSUE TITLE
Create the Testing Blocking Scene

### ISSUE THREAD

**Issue by azsumas** [azsumas/HorrorShooter#24]
# Descripción
- [x] Sketch design of the level. 
- [x] Blocking level in Unity with ProBuilder and ProBuild. 
- [x] Add blocking assets to interact with. 

**EXPECTED RESULTS:**

_Nivel funcional en unity con el que poder hacer testeo de mecánicas._ Imagen del mapa del nivel [aquí](https://github.com/azsumas/HorrorShooter/blob/master/ArtSources/GameDesign/FlowMap.png).

**Comment by MinYoungSoo** [comment]
Final results in https://github.com/azsumas/HorrorShooter/commit/0b28c3264bd26b9eb0d32653ae46adeb7eb5c42f commit.
