### ISSUE TITLE
Fixing the Concept Art

### ISSUE THREAD

**Issue by azsumas** [azsumas/HorrorShooter#26]
# Descripción

- [x] Character 01 
- [x] Character 02 
- [x] Prop 01
- [x] Prop 02
- [x] Environment 01
- [x] Environment 02

**EXPECTED RESULTS:**

_Añadir fondo en los diseños y poner el logo del juego y empresa en la imagen._ Resultados [aquí](https://github.com/azsumas/HorrorShooter/tree/master/ConceptArt).

**Comment by MinYoungSoo** [comment]
Final results in https://github.com/azsumas/HorrorShooter/commit/70ed997f533dbe51945b73a652cbfa36ec4c6ceb commit.
