### ISSUE TITLE
Program Animation in Logo screen

### ISSUE THREAD

**Issue by MinYoungSoo** [azsumas/HorrorShooter#35]
# Descripción
- [x] Animación entrada del logo de la empresa

**EXPECTED RESULTS:**

_Animación fade-in y fade-out del [logo de la empresa](https://github.com/azsumas/HorrorShooter/blob/master/WikiResources/logo.png)._ Resultados en el [scene manager](https://github.com/azsumas/HorrorShooter/blob/master/Assets/Scripts/GameManager/LevelManager.cs).

**Comment by azsumas** [comment]
Dec 11, https://github.com/azsumas/HorrorShooter/commit/e921336e12f2c3dc2d667b80eec6e1bcd7f2708b
