### ISSUE TITLE
Program the Keyboard and Mouse Inputs

### ISSUE THREAD

**Issue by MinYoungSoo** [azsumas/HorrorShooter#42]
# Descripción
- [x] Camera inputs
- [x] Attack and interaction inputs
- [x] Menu inputs

**EXPECTED RESULTS:**

_Inputs de teclado y ratón implementados y funcionales en el juego._ Resultados en proceso.

**Comment by azsumas** [comment]
Oct 17,Camera, KeyBoard, Menu Inputs dc7d1855aa5cb5a9680048c6fc0e535a67bf152f
Oct 17, Attack Inputs 4ca5cf5464283fd588eb30cbe5cbe4ee0511b732
