### ISSUE TITLE
Program the Scene Manager

### ISSUE THREAD

**Issue by MinYoungSoo** [azsumas/HorrorShooter#43]
# Descripción
- [x] Carga y descarga de contenido
- [x] Animación fade in y fade out

**EXPECTED RESULT:**

_Scene manager funcional dentro del juego, que no de errores de memoria ni deje interactuar durante la carga de pantallas._ Resultados en proceso.

**Comment by ivanescario** [comment]
Dec 14, Working 76b807c0d017ce4b66d01d87e7766905132a7db8 358751ad5f36f8271a071f5bf6ab954cd5646f35
Dec 13, Level Manager 646086d418c7c61a9767fc7df75c123495313149
Nov 14, Carga y navegación entre escenas, Animación fade in y fade out bd8dd732d1f6d90f3aeb59d96dd54cbac9d006ff
