### ISSUE TITLE
Program the God Mode

### ISSUE THREAD

**Issue by MinYoungSoo** [azsumas/HorrorShooter#44]
# Descripción
- [x] Volar
- [x] Colisiones
- [ ] Salto entre escenas/mapa
- [ ] Atajos

**EXPECTED RESULT:**

_Añadir las funciones en el juego para el testing en modo God._ Resultados en proceso.

**Comment by azsumas** [comment]
Dec 13, Start working on GODmode. bc59dfd9997c95ab47ce962be3fd3d2a6a58cb9e
Dec 14, Setting Godmode options e9ea25906888774ddf956ac933d6ad110d67a0bc
Dec 14, Godmode Movement collisions working. 215c9f306a2f854f3f7b5fcb75bcb41bb2876588
