### ISSUE TITLE
Model the Player Weapon

### ISSUE THREAD

**Issue by HectorBonada** [azsumas/HorrorShooter#6]
# Descripción
## First concept
- [x] Create the 3D model of the weapon

## Second concept (and final result)
- [x] Create the 3D model of the weapon

**EXPECTED RESULTS:**

_Modelo high y low del arma que utilizará el jugador._ Resultados en el commit https://github.com/azsumas/HorrorShooter/commit/c40ede83da29bf6592485e1475fc56758a2f78d0.

**Comment by MinYoungSoo** [comment]
Final results of the first concept in https://github.com/azsumas/HorrorShooter/commit/797261408739d6fe38c6b4e382a4a15b2c336c9f commit. 
Group decided to do another kind of weapon, model is in progress.
