### ISSUE TITLE
Program the Biped Enemy

### ISSUE THREAD

**Issue by HectorBonada** [azsumas/HorrorShooter#9]
# Descripción
- [x] Patrol 
- [x] Attack
- [x] Die

**EXPECTED RESULT:** 

_Programación de la IA del enemigo bípedo, respetando las mecánicas propuestas por el [HDD](https://github.com/azsumas/HorrorShooter/wiki/Project-Description#enemies)._ Resultados en este [script](https://github.com/azsumas/HorrorShooter/blob/master/Assets/Scripts/Enemies/EnemyBehaviour.cs). Implementación aún en proceso y testeo.

**Comment by azsumas** [comment]
Enemy can walk, patrol, have nav mesh, and chase for the player. 
Need to do damage, and take damage, die (done it). 👍 
Check parameters for better customization of the enemy like speed, line of sight need it, damage, life points.

**Comment by azsumas** [comment]
Done it 99%

**Comment by azsumas** [comment]
Nov 14, Errors Solving cd81d965ab2f46e71529ecc7f7fd7b60a31d41bf
Nov 13, Implement Enemy to the scene 8ebe3d741e224e54272b25a8ae3eed16d0cc6269
Nov 13, Enemy working, c707f27ee44060eb07f29c79e42ee4d4282f4b52
Nov 6, Error solving 72510acce1d77325e817f4521462c1a47a9b1b3e
Nov 6, Move Chase working 1186e810ab2df9cfc91cd1040d388da832abbb65
Nov 3, Enemy sight logic, e2d4b6e28c64a8a393e2b31539f1c2ec30b36ac3 70f50c32d7448f7fd3b7131ea4e1acb8eacf9119
Oct 23, Enemy movement logic working 64813cace9f2b5e7a215f24df6b69e1ef366d10d
